branches:
  only:
  - master
language: python
os:
  - linux
  - osx
  - windows
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

jobs:
  exclude:
  - os: osx
    python: "3.6"
  - os: osx
    python: "3.7"
  - os: osx
    python: "3.8"
  - os: windows
    python: "3.6"
  - os: windows
    python: "3.7"
  - os: windows
    python: "3.8"

before_script:
- echo "this is before_script"

script:
- |
  (
    echo "this is script"
    set -Eeuo pipefail
    set -x
    python -m unittest discover paddle1to2/tests/
    python setup.py sdist bdist_wheel
    pip install dist/paddle1to2*.whl
    cd /
    python -m unittest discover paddle1to2.tests.test_refactor
    paddle1to2 -h
  )

after_script:
- echo "this is after_script"

after_success:
- echo "this is after_success"
