branches:
  only:
  - master
language: python
os:
  - linux
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

jobs:
  include:
    - name: "python: 3.5 on macOS"
      os: osx
      osx_image: xcode11
      language: shell
      env: PYTHON=35
      before_script:
        - python3 --version
      script:
        - python3 -m unittest discover paddle1to2/tests/ 
        - python3 setup.py sdist bdist_wheel
        - pip3 install dist/paddle1to2*.whl
        - rm -rf ./*
        - python3 -m unittest discover paddle1to2.tests.test_refactor
    - name: "python: 3.5 on Windows"
      os: windows
      language: shell
      before_install:
        - choco install python --version 3.5.4
        - python -m pip install --upgrade pip
        - pip3 install wheel
      env: PATH=/c/Python35:/c/Python35/Scripts:$PATH

before_install:
- echo "this is before_install"

before_script:
- echo "this is before_script"
- python --version

script:
- echo "this is script"
- |
  (
    python -m unittest discover paddle1to2/tests/
    python setup.py sdist bdist_wheel
    pip3 install dist/paddle1to2*.whl
    cd /
    python -m unittest discover paddle1to2.tests.test_refactor
  )

after_script:
- echo "this is after_script"
- paddle1to2 -h

after_success:
- echo "this is after_success"
