branches:
  only:
  - master
language: python
os:
  - linux
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

jobs:
  include:
    - name: "python 3.5 on macOS"
      os: osx
      osx_image: xcode11
      language: shell
      env: PYTHON=35
    - name: "python3.5 on Windows"
      os: windows
      language: shell
      before_install:
        - choco install python --version 3.5.0
        - python -m pip install --upgrade pip
      env: PATH=/c/Python35:/c/Python35/Scripts:$PATH

before_script:
- echo "this is before_script"

script:
- |
  (
    echo "this is script"
    python --version
    set -Eeuo pipefail
    set -x
    python -m unittest discover paddle1to2/tests/
    python setup.py sdist bdist_wheel
    pip install dist/paddle1to2*.whl
    cd /
    python -m unittest discover paddle1to2.tests.test_refactor
    paddle1to2 -h
  )

after_script:
- echo "this is after_script"

after_success:
- echo "this is after_success"
