branches:
  only:
  - master
language: python
os:
  - linux
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

jobs:
  include:
    - name: "python: 3.5 on macOS"
      os: osx
      osx_image: xcode11
      language: shell
      env: PYTHON=35
      before_script:
        - python3 --version
      script:
        - python3 -m unittest discover paddle_upgrade_tool/tests/
        - python3 setup.py sdist bdist_wheel
        - pip3 install dist/paddle_upgrade_tool*.whl
        - cd ..
        - python3 -m unittest discover paddle_upgrade_tool.tests.test_refactor
      after_success: ""
    - name: "python: 3.5 on Windows"
      os: windows
      language: shell
      before_install:
        - choco install python --version 3.5.4
        - python -m pip install --upgrade pip
        - pip3 install wheel
      script:
        - python -m unittest discover paddle_upgrade_tool/tests/
        - python setup.py sdist bdist_wheel
        - pip3 install dist/paddle_upgrade_tool*.whl
        - cd ..
        - python -m unittest discover paddle_upgrade_tool.tests.test_refactor
      after_success: ""
      env: PATH=/c/Python35:/c/Python35/Scripts:$PATH

before_install:
- echo "this is before_install"

before_script:
- echo "this is before_script"
- python --version

script:
- echo "this is script"
- |
  (
    python -m unittest discover paddle_upgrade_tool/tests/
    python setup.py sdist bdist_wheel
    pip3 install dist/paddle_upgrade_tool*.whl
    cd ..
    python -m unittest discover paddle_upgrade_tool.tests.test_refactor
    paddle_upgrade_tool -h
    pip3 install pytest-cov coveralls
    cd paddle_upgrade_tool
    pytest --cov=paddle_upgrade_tool
  )

after_script:
- echo "this is after_script"

after_success:
- echo "this is after_success"
- coveralls
